// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/map_unittest.proto

#ifndef PROTOBUF_google_2fprotobuf_2fmap_5funittest_2eproto__INCLUDED
#define PROTOBUF_google_2fprotobuf_2fmap_5funittest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/protobuf/unittest.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_unittest {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
void protobuf_AssignDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5funittest_2eproto();

class TestMap;
class TestMessageMap;
class TestSameTypeMap;
class TestRequiredMessageMap;

enum MapEnum {
  MAP_ENUM_FOO = 0,
  MAP_ENUM_BAR = 1,
  MAP_ENUM_BAZ = 2,
  MapEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MapEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MapEnum_IsValid(int value);
const MapEnum MapEnum_MIN = MAP_ENUM_FOO;
const MapEnum MapEnum_MAX = MAP_ENUM_BAZ;
const int MapEnum_ARRAYSIZE = MapEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* MapEnum_descriptor();
inline const ::std::string& MapEnum_Name(MapEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    MapEnum_descriptor(), value);
}
inline bool MapEnum_Parse(
    const ::std::string& name, MapEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MapEnum>(
    MapEnum_descriptor(), name, value);
}
// ===================================================================

class TestMap : public ::google::protobuf::Message {
 public:
  TestMap();
  virtual ~TestMap();

  TestMap(const TestMap& from);

  inline TestMap& operator=(const TestMap& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMap& default_instance();

  void Swap(TestMap* other);

  // implements Message ----------------------------------------------

  inline TestMap* New() const { return New(NULL); }

  TestMap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMap& from);
  void MergeFrom(const TestMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, int32> map_int32_int32 = 1;
  inline int map_int32_int32_size() const;
  inline void clear_map_int32_int32();
  static const int kMapInt32Int32FieldNumber = 1;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      map_int32_int32() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_map_int32_int32();

  // map<int64, int64> map_int64_int64 = 2;
  inline int map_int64_int64_size() const;
  inline void clear_map_int64_int64();
  static const int kMapInt64Int64FieldNumber = 2;
  inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
      map_int64_int64() const;
  inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
      mutable_map_int64_int64();

  // map<uint32, uint32> map_uint32_uint32 = 3;
  inline int map_uint32_uint32_size() const;
  inline void clear_map_uint32_uint32();
  static const int kMapUint32Uint32FieldNumber = 3;
  inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
      map_uint32_uint32() const;
  inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
      mutable_map_uint32_uint32();

  // map<uint64, uint64> map_uint64_uint64 = 4;
  inline int map_uint64_uint64_size() const;
  inline void clear_map_uint64_uint64();
  static const int kMapUint64Uint64FieldNumber = 4;
  inline const ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >&
      map_uint64_uint64() const;
  inline ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >*
      mutable_map_uint64_uint64();

  // map<sint32, sint32> map_sint32_sint32 = 5;
  inline int map_sint32_sint32_size() const;
  inline void clear_map_sint32_sint32();
  static const int kMapSint32Sint32FieldNumber = 5;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      map_sint32_sint32() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_map_sint32_sint32();

  // map<sint64, sint64> map_sint64_sint64 = 6;
  inline int map_sint64_sint64_size() const;
  inline void clear_map_sint64_sint64();
  static const int kMapSint64Sint64FieldNumber = 6;
  inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
      map_sint64_sint64() const;
  inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
      mutable_map_sint64_sint64();

  // map<fixed32, fixed32> map_fixed32_fixed32 = 7;
  inline int map_fixed32_fixed32_size() const;
  inline void clear_map_fixed32_fixed32();
  static const int kMapFixed32Fixed32FieldNumber = 7;
  inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
      map_fixed32_fixed32() const;
  inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
      mutable_map_fixed32_fixed32();

  // map<fixed64, fixed64> map_fixed64_fixed64 = 8;
  inline int map_fixed64_fixed64_size() const;
  inline void clear_map_fixed64_fixed64();
  static const int kMapFixed64Fixed64FieldNumber = 8;
  inline const ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >&
      map_fixed64_fixed64() const;
  inline ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >*
      mutable_map_fixed64_fixed64();

  // map<sfixed32, sfixed32> map_sfixed32_sfixed32 = 9;
  inline int map_sfixed32_sfixed32_size() const;
  inline void clear_map_sfixed32_sfixed32();
  static const int kMapSfixed32Sfixed32FieldNumber = 9;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      map_sfixed32_sfixed32() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_map_sfixed32_sfixed32();

  // map<sfixed64, sfixed64> map_sfixed64_sfixed64 = 10;
  inline int map_sfixed64_sfixed64_size() const;
  inline void clear_map_sfixed64_sfixed64();
  static const int kMapSfixed64Sfixed64FieldNumber = 10;
  inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
      map_sfixed64_sfixed64() const;
  inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
      mutable_map_sfixed64_sfixed64();

  // map<int32, float> map_int32_float = 11;
  inline int map_int32_float_size() const;
  inline void clear_map_int32_float();
  static const int kMapInt32FloatFieldNumber = 11;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, float >&
      map_int32_float() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, float >*
      mutable_map_int32_float();

  // map<int32, double> map_int32_double = 12;
  inline int map_int32_double_size() const;
  inline void clear_map_int32_double();
  static const int kMapInt32DoubleFieldNumber = 12;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, double >&
      map_int32_double() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, double >*
      mutable_map_int32_double();

  // map<bool, bool> map_bool_bool = 13;
  inline int map_bool_bool_size() const;
  inline void clear_map_bool_bool();
  static const int kMapBoolBoolFieldNumber = 13;
  inline const ::google::protobuf::Map< bool, bool >&
      map_bool_bool() const;
  inline ::google::protobuf::Map< bool, bool >*
      mutable_map_bool_bool();

  // map<string, string> map_string_string = 14;
  inline int map_string_string_size() const;
  inline void clear_map_string_string();
  static const int kMapStringStringFieldNumber = 14;
  inline const ::google::protobuf::Map< ::std::string, ::std::string >&
      map_string_string() const;
  inline ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_map_string_string();

  // map<int32, bytes> map_int32_bytes = 15;
  inline int map_int32_bytes_size() const;
  inline void clear_map_int32_bytes();
  static const int kMapInt32BytesFieldNumber = 15;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::std::string >&
      map_int32_bytes() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::std::string >*
      mutable_map_int32_bytes();

  // map<int32, .protobuf_unittest.MapEnum> map_int32_enum = 16;
  inline int map_int32_enum_size() const;
  inline void clear_map_int32_enum();
  static const int kMapInt32EnumFieldNumber = 16;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, MapEnum >&
      map_int32_enum() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, MapEnum >*
      mutable_map_int32_enum();

  // map<int32, .protobuf_unittest.ForeignMessage> map_int32_foreign_message = 17;
  inline int map_int32_foreign_message_size() const;
  inline void clear_map_int32_foreign_message();
  static const int kMapInt32ForeignMessageFieldNumber = 17;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::ForeignMessage >&
      map_int32_foreign_message() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::ForeignMessage >*
      mutable_map_int32_foreign_message();

  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_INT32, 0>
      TestMap_MapInt32Int32Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::google::protobuf::int32,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_INT32, 0 > map_int32_int32_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::FieldDescriptor::TYPE_INT64,
      ::google::protobuf::FieldDescriptor::TYPE_INT64, 0>
      TestMap_MapInt64Int64Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int64, ::google::protobuf::int64,::google::protobuf::FieldDescriptor::TYPE_INT64, ::google::protobuf::FieldDescriptor::TYPE_INT64, 0 > map_int64_int64_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::FieldDescriptor::TYPE_UINT32,
      ::google::protobuf::FieldDescriptor::TYPE_UINT32, 0>
      TestMap_MapUint32Uint32Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::uint32, ::google::protobuf::uint32,::google::protobuf::FieldDescriptor::TYPE_UINT32, ::google::protobuf::FieldDescriptor::TYPE_UINT32, 0 > map_uint32_uint32_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::uint64, ::google::protobuf::uint64,
      ::google::protobuf::FieldDescriptor::TYPE_UINT64,
      ::google::protobuf::FieldDescriptor::TYPE_UINT64, 0>
      TestMap_MapUint64Uint64Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::uint64, ::google::protobuf::uint64,::google::protobuf::FieldDescriptor::TYPE_UINT64, ::google::protobuf::FieldDescriptor::TYPE_UINT64, 0 > map_uint64_uint64_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::FieldDescriptor::TYPE_SINT32,
      ::google::protobuf::FieldDescriptor::TYPE_SINT32, 0>
      TestMap_MapSint32Sint32Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::google::protobuf::int32,::google::protobuf::FieldDescriptor::TYPE_SINT32, ::google::protobuf::FieldDescriptor::TYPE_SINT32, 0 > map_sint32_sint32_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::FieldDescriptor::TYPE_SINT64,
      ::google::protobuf::FieldDescriptor::TYPE_SINT64, 0>
      TestMap_MapSint64Sint64Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int64, ::google::protobuf::int64,::google::protobuf::FieldDescriptor::TYPE_SINT64, ::google::protobuf::FieldDescriptor::TYPE_SINT64, 0 > map_sint64_sint64_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::FieldDescriptor::TYPE_FIXED32,
      ::google::protobuf::FieldDescriptor::TYPE_FIXED32, 0>
      TestMap_MapFixed32Fixed32Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::uint32, ::google::protobuf::uint32,::google::protobuf::FieldDescriptor::TYPE_FIXED32, ::google::protobuf::FieldDescriptor::TYPE_FIXED32, 0 > map_fixed32_fixed32_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::uint64, ::google::protobuf::uint64,
      ::google::protobuf::FieldDescriptor::TYPE_FIXED64,
      ::google::protobuf::FieldDescriptor::TYPE_FIXED64, 0>
      TestMap_MapFixed64Fixed64Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::uint64, ::google::protobuf::uint64,::google::protobuf::FieldDescriptor::TYPE_FIXED64, ::google::protobuf::FieldDescriptor::TYPE_FIXED64, 0 > map_fixed64_fixed64_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::FieldDescriptor::TYPE_SFIXED32,
      ::google::protobuf::FieldDescriptor::TYPE_SFIXED32, 0>
      TestMap_MapSfixed32Sfixed32Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::google::protobuf::int32,::google::protobuf::FieldDescriptor::TYPE_SFIXED32, ::google::protobuf::FieldDescriptor::TYPE_SFIXED32, 0 > map_sfixed32_sfixed32_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::FieldDescriptor::TYPE_SFIXED64,
      ::google::protobuf::FieldDescriptor::TYPE_SFIXED64, 0>
      TestMap_MapSfixed64Sfixed64Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int64, ::google::protobuf::int64,::google::protobuf::FieldDescriptor::TYPE_SFIXED64, ::google::protobuf::FieldDescriptor::TYPE_SFIXED64, 0 > map_sfixed64_sfixed64_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, float,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_FLOAT, 0>
      TestMap_MapInt32FloatEntry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, float,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_FLOAT, 0 > map_int32_float_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, double,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_DOUBLE, 0>
      TestMap_MapInt32DoubleEntry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, double,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_DOUBLE, 0 > map_int32_double_;
  typedef ::google::protobuf::internal::MapEntry<
      bool, bool,
      ::google::protobuf::FieldDescriptor::TYPE_BOOL,
      ::google::protobuf::FieldDescriptor::TYPE_BOOL, 0>
      TestMap_MapBoolBoolEntry;
  ::google::protobuf::internal::MapField< bool, bool,::google::protobuf::FieldDescriptor::TYPE_BOOL, ::google::protobuf::FieldDescriptor::TYPE_BOOL, 0 > map_bool_bool_;
  typedef ::google::protobuf::internal::MapEntry<
      ::std::string, ::std::string,
      ::google::protobuf::FieldDescriptor::TYPE_STRING,
      ::google::protobuf::FieldDescriptor::TYPE_STRING, 0>
      TestMap_MapStringStringEntry;
  ::google::protobuf::internal::MapField< ::std::string, ::std::string,::google::protobuf::FieldDescriptor::TYPE_STRING, ::google::protobuf::FieldDescriptor::TYPE_STRING, 0 > map_string_string_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::std::string,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_BYTES, 0>
      TestMap_MapInt32BytesEntry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::std::string,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_BYTES, 0 > map_int32_bytes_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, MapEnum,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_ENUM, 0>
      TestMap_MapInt32EnumEntry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, MapEnum,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_ENUM, 0 > map_int32_enum_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::protobuf_unittest::ForeignMessage,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_MESSAGE, 0>
      TestMap_MapInt32ForeignMessageEntry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::protobuf_unittest::ForeignMessage,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_MESSAGE, 0 > map_int32_foreign_message_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5funittest_2eproto();

  void InitAsDefaultInstance();
  static TestMap* default_instance_;
};
// -------------------------------------------------------------------

class TestMessageMap : public ::google::protobuf::Message {
 public:
  TestMessageMap();
  virtual ~TestMessageMap();

  TestMessageMap(const TestMessageMap& from);

  inline TestMessageMap& operator=(const TestMessageMap& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessageMap& default_instance();

  void Swap(TestMessageMap* other);

  // implements Message ----------------------------------------------

  inline TestMessageMap* New() const { return New(NULL); }

  TestMessageMap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMessageMap& from);
  void MergeFrom(const TestMessageMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestMessageMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .protobuf_unittest.TestAllTypes> map_int32_message = 1;
  inline int map_int32_message_size() const;
  inline void clear_map_int32_message();
  static const int kMapInt32MessageFieldNumber = 1;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::TestAllTypes >&
      map_int32_message() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::TestAllTypes >*
      mutable_map_int32_message();

  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestMessageMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::protobuf_unittest::TestAllTypes,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_MESSAGE, 0>
      TestMessageMap_MapInt32MessageEntry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::protobuf_unittest::TestAllTypes,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_MESSAGE, 0 > map_int32_message_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5funittest_2eproto();

  void InitAsDefaultInstance();
  static TestMessageMap* default_instance_;
};
// -------------------------------------------------------------------

class TestSameTypeMap : public ::google::protobuf::Message {
 public:
  TestSameTypeMap();
  virtual ~TestSameTypeMap();

  TestSameTypeMap(const TestSameTypeMap& from);

  inline TestSameTypeMap& operator=(const TestSameTypeMap& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestSameTypeMap& default_instance();

  void Swap(TestSameTypeMap* other);

  // implements Message ----------------------------------------------

  inline TestSameTypeMap* New() const { return New(NULL); }

  TestSameTypeMap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestSameTypeMap& from);
  void MergeFrom(const TestSameTypeMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestSameTypeMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, int32> map1 = 1;
  inline int map1_size() const;
  inline void clear_map1();
  static const int kMap1FieldNumber = 1;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      map1() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_map1();

  // map<int32, int32> map2 = 2;
  inline int map2_size() const;
  inline void clear_map2();
  static const int kMap2FieldNumber = 2;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      map2() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_map2();

  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestSameTypeMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_INT32, 0>
      TestSameTypeMap_Map1Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::google::protobuf::int32,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_INT32, 0 > map1_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_INT32, 0>
      TestSameTypeMap_Map2Entry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::google::protobuf::int32,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_INT32, 0 > map2_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5funittest_2eproto();

  void InitAsDefaultInstance();
  static TestSameTypeMap* default_instance_;
};
// -------------------------------------------------------------------

class TestRequiredMessageMap : public ::google::protobuf::Message {
 public:
  TestRequiredMessageMap();
  virtual ~TestRequiredMessageMap();

  TestRequiredMessageMap(const TestRequiredMessageMap& from);

  inline TestRequiredMessageMap& operator=(const TestRequiredMessageMap& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestRequiredMessageMap& default_instance();

  void Swap(TestRequiredMessageMap* other);

  // implements Message ----------------------------------------------

  inline TestRequiredMessageMap* New() const { return New(NULL); }

  TestRequiredMessageMap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestRequiredMessageMap& from);
  void MergeFrom(const TestRequiredMessageMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestRequiredMessageMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .protobuf_unittest.TestRequired> map_field = 1;
  inline int map_field_size() const;
  inline void clear_map_field();
  static const int kMapFieldFieldNumber = 1;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::TestRequired >&
      map_field() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::TestRequired >*
      mutable_map_field();

  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestRequiredMessageMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::protobuf_unittest::TestRequired,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_MESSAGE, 0>
      TestRequiredMessageMap_MapFieldEntry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::protobuf_unittest::TestRequired,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_MESSAGE, 0 > map_field_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fmap_5funittest_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5funittest_2eproto();

  void InitAsDefaultInstance();
  static TestRequiredMessageMap* default_instance_;
};
// ===================================================================


// ===================================================================

// TestMap

// map<int32, int32> map_int32_int32 = 1;
inline int TestMap::map_int32_int32_size() const {
  return map_int32_int32_.size();
}
inline void TestMap::clear_map_int32_int32() {
  map_int32_int32_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
TestMap::map_int32_int32() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_int32_int32)
  return map_int32_int32_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
TestMap::mutable_map_int32_int32() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_int32_int32)
  return map_int32_int32_.MutableMap();
}

// map<int64, int64> map_int64_int64 = 2;
inline int TestMap::map_int64_int64_size() const {
  return map_int64_int64_.size();
}
inline void TestMap::clear_map_int64_int64() {
  map_int64_int64_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
TestMap::map_int64_int64() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_int64_int64)
  return map_int64_int64_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
TestMap::mutable_map_int64_int64() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_int64_int64)
  return map_int64_int64_.MutableMap();
}

// map<uint32, uint32> map_uint32_uint32 = 3;
inline int TestMap::map_uint32_uint32_size() const {
  return map_uint32_uint32_.size();
}
inline void TestMap::clear_map_uint32_uint32() {
  map_uint32_uint32_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
TestMap::map_uint32_uint32() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_uint32_uint32)
  return map_uint32_uint32_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
TestMap::mutable_map_uint32_uint32() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_uint32_uint32)
  return map_uint32_uint32_.MutableMap();
}

// map<uint64, uint64> map_uint64_uint64 = 4;
inline int TestMap::map_uint64_uint64_size() const {
  return map_uint64_uint64_.size();
}
inline void TestMap::clear_map_uint64_uint64() {
  map_uint64_uint64_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >&
TestMap::map_uint64_uint64() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_uint64_uint64)
  return map_uint64_uint64_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >*
TestMap::mutable_map_uint64_uint64() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_uint64_uint64)
  return map_uint64_uint64_.MutableMap();
}

// map<sint32, sint32> map_sint32_sint32 = 5;
inline int TestMap::map_sint32_sint32_size() const {
  return map_sint32_sint32_.size();
}
inline void TestMap::clear_map_sint32_sint32() {
  map_sint32_sint32_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
TestMap::map_sint32_sint32() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_sint32_sint32)
  return map_sint32_sint32_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
TestMap::mutable_map_sint32_sint32() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_sint32_sint32)
  return map_sint32_sint32_.MutableMap();
}

// map<sint64, sint64> map_sint64_sint64 = 6;
inline int TestMap::map_sint64_sint64_size() const {
  return map_sint64_sint64_.size();
}
inline void TestMap::clear_map_sint64_sint64() {
  map_sint64_sint64_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
TestMap::map_sint64_sint64() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_sint64_sint64)
  return map_sint64_sint64_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
TestMap::mutable_map_sint64_sint64() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_sint64_sint64)
  return map_sint64_sint64_.MutableMap();
}

// map<fixed32, fixed32> map_fixed32_fixed32 = 7;
inline int TestMap::map_fixed32_fixed32_size() const {
  return map_fixed32_fixed32_.size();
}
inline void TestMap::clear_map_fixed32_fixed32() {
  map_fixed32_fixed32_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
TestMap::map_fixed32_fixed32() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_fixed32_fixed32)
  return map_fixed32_fixed32_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
TestMap::mutable_map_fixed32_fixed32() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_fixed32_fixed32)
  return map_fixed32_fixed32_.MutableMap();
}

// map<fixed64, fixed64> map_fixed64_fixed64 = 8;
inline int TestMap::map_fixed64_fixed64_size() const {
  return map_fixed64_fixed64_.size();
}
inline void TestMap::clear_map_fixed64_fixed64() {
  map_fixed64_fixed64_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >&
TestMap::map_fixed64_fixed64() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_fixed64_fixed64)
  return map_fixed64_fixed64_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >*
TestMap::mutable_map_fixed64_fixed64() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_fixed64_fixed64)
  return map_fixed64_fixed64_.MutableMap();
}

// map<sfixed32, sfixed32> map_sfixed32_sfixed32 = 9;
inline int TestMap::map_sfixed32_sfixed32_size() const {
  return map_sfixed32_sfixed32_.size();
}
inline void TestMap::clear_map_sfixed32_sfixed32() {
  map_sfixed32_sfixed32_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
TestMap::map_sfixed32_sfixed32() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_sfixed32_sfixed32)
  return map_sfixed32_sfixed32_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
TestMap::mutable_map_sfixed32_sfixed32() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_sfixed32_sfixed32)
  return map_sfixed32_sfixed32_.MutableMap();
}

// map<sfixed64, sfixed64> map_sfixed64_sfixed64 = 10;
inline int TestMap::map_sfixed64_sfixed64_size() const {
  return map_sfixed64_sfixed64_.size();
}
inline void TestMap::clear_map_sfixed64_sfixed64() {
  map_sfixed64_sfixed64_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
TestMap::map_sfixed64_sfixed64() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_sfixed64_sfixed64)
  return map_sfixed64_sfixed64_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
TestMap::mutable_map_sfixed64_sfixed64() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_sfixed64_sfixed64)
  return map_sfixed64_sfixed64_.MutableMap();
}

// map<int32, float> map_int32_float = 11;
inline int TestMap::map_int32_float_size() const {
  return map_int32_float_.size();
}
inline void TestMap::clear_map_int32_float() {
  map_int32_float_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, float >&
TestMap::map_int32_float() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_int32_float)
  return map_int32_float_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, float >*
TestMap::mutable_map_int32_float() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_int32_float)
  return map_int32_float_.MutableMap();
}

// map<int32, double> map_int32_double = 12;
inline int TestMap::map_int32_double_size() const {
  return map_int32_double_.size();
}
inline void TestMap::clear_map_int32_double() {
  map_int32_double_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, double >&
TestMap::map_int32_double() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_int32_double)
  return map_int32_double_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, double >*
TestMap::mutable_map_int32_double() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_int32_double)
  return map_int32_double_.MutableMap();
}

// map<bool, bool> map_bool_bool = 13;
inline int TestMap::map_bool_bool_size() const {
  return map_bool_bool_.size();
}
inline void TestMap::clear_map_bool_bool() {
  map_bool_bool_.Clear();
}
inline const ::google::protobuf::Map< bool, bool >&
TestMap::map_bool_bool() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_bool_bool)
  return map_bool_bool_.GetMap();
}
inline ::google::protobuf::Map< bool, bool >*
TestMap::mutable_map_bool_bool() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_bool_bool)
  return map_bool_bool_.MutableMap();
}

// map<string, string> map_string_string = 14;
inline int TestMap::map_string_string_size() const {
  return map_string_string_.size();
}
inline void TestMap::clear_map_string_string() {
  map_string_string_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
TestMap::map_string_string() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_string_string)
  return map_string_string_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
TestMap::mutable_map_string_string() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_string_string)
  return map_string_string_.MutableMap();
}

// map<int32, bytes> map_int32_bytes = 15;
inline int TestMap::map_int32_bytes_size() const {
  return map_int32_bytes_.size();
}
inline void TestMap::clear_map_int32_bytes() {
  map_int32_bytes_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::std::string >&
TestMap::map_int32_bytes() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_int32_bytes)
  return map_int32_bytes_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::std::string >*
TestMap::mutable_map_int32_bytes() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_int32_bytes)
  return map_int32_bytes_.MutableMap();
}

// map<int32, .protobuf_unittest.MapEnum> map_int32_enum = 16;
inline int TestMap::map_int32_enum_size() const {
  return map_int32_enum_.size();
}
inline void TestMap::clear_map_int32_enum() {
  map_int32_enum_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, MapEnum >&
TestMap::map_int32_enum() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_int32_enum)
  return map_int32_enum_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, MapEnum >*
TestMap::mutable_map_int32_enum() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_int32_enum)
  return map_int32_enum_.MutableMap();
}

// map<int32, .protobuf_unittest.ForeignMessage> map_int32_foreign_message = 17;
inline int TestMap::map_int32_foreign_message_size() const {
  return map_int32_foreign_message_.size();
}
inline void TestMap::clear_map_int32_foreign_message() {
  map_int32_foreign_message_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::ForeignMessage >&
TestMap::map_int32_foreign_message() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMap.map_int32_foreign_message)
  return map_int32_foreign_message_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::ForeignMessage >*
TestMap::mutable_map_int32_foreign_message() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMap.map_int32_foreign_message)
  return map_int32_foreign_message_.MutableMap();
}

// -------------------------------------------------------------------

// TestMessageMap

// map<int32, .protobuf_unittest.TestAllTypes> map_int32_message = 1;
inline int TestMessageMap::map_int32_message_size() const {
  return map_int32_message_.size();
}
inline void TestMessageMap::clear_map_int32_message() {
  map_int32_message_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::TestAllTypes >&
TestMessageMap::map_int32_message() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestMessageMap.map_int32_message)
  return map_int32_message_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::TestAllTypes >*
TestMessageMap::mutable_map_int32_message() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestMessageMap.map_int32_message)
  return map_int32_message_.MutableMap();
}

// -------------------------------------------------------------------

// TestSameTypeMap

// map<int32, int32> map1 = 1;
inline int TestSameTypeMap::map1_size() const {
  return map1_.size();
}
inline void TestSameTypeMap::clear_map1() {
  map1_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
TestSameTypeMap::map1() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestSameTypeMap.map1)
  return map1_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
TestSameTypeMap::mutable_map1() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestSameTypeMap.map1)
  return map1_.MutableMap();
}

// map<int32, int32> map2 = 2;
inline int TestSameTypeMap::map2_size() const {
  return map2_.size();
}
inline void TestSameTypeMap::clear_map2() {
  map2_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
TestSameTypeMap::map2() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestSameTypeMap.map2)
  return map2_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
TestSameTypeMap::mutable_map2() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestSameTypeMap.map2)
  return map2_.MutableMap();
}

// -------------------------------------------------------------------

// TestRequiredMessageMap

// map<int32, .protobuf_unittest.TestRequired> map_field = 1;
inline int TestRequiredMessageMap::map_field_size() const {
  return map_field_.size();
}
inline void TestRequiredMessageMap::clear_map_field() {
  map_field_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::TestRequired >&
TestRequiredMessageMap::map_field() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestRequiredMessageMap.map_field)
  return map_field_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::protobuf_unittest::TestRequired >*
TestRequiredMessageMap::mutable_map_field() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestRequiredMessageMap.map_field)
  return map_field_.MutableMap();
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf_unittest

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::protobuf_unittest::MapEnum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf_unittest::MapEnum>() {
  return ::protobuf_unittest::MapEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2fprotobuf_2fmap_5funittest_2eproto__INCLUDED
