// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/map_lite_unittest.proto

#ifndef PROTOBUF_google_2fprotobuf_2fmap_5flite_5funittest_2eproto__INCLUDED
#define PROTOBUF_google_2fprotobuf_2fmap_5flite_5funittest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
// @@protoc_insertion_point(includes)

namespace protobuf_unittest {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_google_2fprotobuf_2fmap_5flite_5funittest_2eproto();
void protobuf_AssignDesc_google_2fprotobuf_2fmap_5flite_5funittest_2eproto();
void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5flite_5funittest_2eproto();

class MapLite;

// ===================================================================

class MapLite : public ::google::protobuf::MessageLite {
 public:
  MapLite();
  virtual ~MapLite();

  MapLite(const MapLite& from);

  inline MapLite& operator=(const MapLite& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const MapLite& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MapLite* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MapLite* other);

  // implements Message ----------------------------------------------

  inline MapLite* New() const { return New(NULL); }

  MapLite* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MapLite& from);
  void MergeFrom(const MapLite& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MapLite* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, int32> map_field = 1;
  inline int map_field_size() const;
  inline void clear_map_field();
  static const int kMapFieldFieldNumber = 1;
  inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      map_field() const;
  inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_map_field();

  // @@protoc_insertion_point(class_scope:protobuf_unittest.MapLite)
 private:

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  typedef ::google::protobuf::internal::MapEntry<
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::FieldDescriptor::TYPE_INT32,
      ::google::protobuf::FieldDescriptor::TYPE_INT32, 0>
      MapLite_MapFieldEntry;
  ::google::protobuf::internal::MapField< ::google::protobuf::int32, ::google::protobuf::int32,::google::protobuf::FieldDescriptor::TYPE_INT32, ::google::protobuf::FieldDescriptor::TYPE_INT32, 0 > map_field_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5flite_5funittest_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5flite_5funittest_2eproto();
  #endif
  friend void protobuf_AssignDesc_google_2fprotobuf_2fmap_5flite_5funittest_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5flite_5funittest_2eproto();

  void InitAsDefaultInstance();
  static MapLite* default_instance_;
};
// ===================================================================


// ===================================================================

// MapLite

// map<int32, int32> map_field = 1;
inline int MapLite::map_field_size() const {
  return map_field_.size();
}
inline void MapLite::clear_map_field() {
  map_field_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
MapLite::map_field() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.MapLite.map_field)
  return map_field_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
MapLite::mutable_map_field() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.MapLite.map_field)
  return map_field_.MutableMap();
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf_unittest

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2fprotobuf_2fmap_5flite_5funittest_2eproto__INCLUDED
