// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/unittest_preserve_unknown_enum.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "google/protobuf/unittest_preserve_unknown_enum.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto2_preserve_unknown_enum_unittest {

namespace {

const ::google::protobuf::Descriptor* MyMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MyMessage_reflection_ = NULL;
struct MyMessageOneofInstance {
  int oneof_e_1_;
  int oneof_e_2_;
}* MyMessage_default_oneof_instance_ = NULL;
const ::google::protobuf::Descriptor* MyMessagePlusExtra_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MyMessagePlusExtra_reflection_ = NULL;
struct MyMessagePlusExtraOneofInstance {
  int oneof_e_1_;
  int oneof_e_2_;
}* MyMessagePlusExtra_default_oneof_instance_ = NULL;
const ::google::protobuf::EnumDescriptor* MyEnum_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MyEnumPlusExtra_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto() {
  protobuf_AddDesc_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "google/protobuf/unittest_preserve_unknown_enum.proto");
  GOOGLE_CHECK(file != NULL);
  MyMessage_descriptor_ = file->message_type(0);
  static const int MyMessage_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, e_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, repeated_e_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, repeated_packed_e_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(MyMessage_default_oneof_instance_, oneof_e_1_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(MyMessage_default_oneof_instance_, oneof_e_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, o_),
  };
  MyMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MyMessage_descriptor_,
      MyMessage::default_instance_,
      MyMessage_offsets_,
      -1,
      -1,
      -1,
      MyMessage_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, _oneof_case_[0]),
      sizeof(MyMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, _is_default_instance_));
  MyMessagePlusExtra_descriptor_ = file->message_type(1);
  static const int MyMessagePlusExtra_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessagePlusExtra, e_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessagePlusExtra, repeated_e_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessagePlusExtra, repeated_packed_e_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(MyMessagePlusExtra_default_oneof_instance_, oneof_e_1_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(MyMessagePlusExtra_default_oneof_instance_, oneof_e_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessagePlusExtra, o_),
  };
  MyMessagePlusExtra_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MyMessagePlusExtra_descriptor_,
      MyMessagePlusExtra::default_instance_,
      MyMessagePlusExtra_offsets_,
      -1,
      -1,
      -1,
      MyMessagePlusExtra_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessagePlusExtra, _oneof_case_[0]),
      sizeof(MyMessagePlusExtra),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessagePlusExtra, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessagePlusExtra, _is_default_instance_));
  MyEnum_descriptor_ = file->enum_type(0);
  MyEnumPlusExtra_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MyMessage_descriptor_, &MyMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MyMessagePlusExtra_descriptor_, &MyMessagePlusExtra::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto() {
  delete MyMessage::default_instance_;
  delete MyMessage_default_oneof_instance_;
  delete MyMessage_reflection_;
  delete MyMessagePlusExtra::default_instance_;
  delete MyMessagePlusExtra_default_oneof_instance_;
  delete MyMessagePlusExtra_reflection_;
}

void protobuf_AddDesc_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n4google/protobuf/unittest_preserve_unkn"
    "own_enum.proto\022%proto2_preserve_unknown_"
    "enum_unittest\"\343\002\n\tMyMessage\0228\n\001e\030\001 \001(\0162-"
    ".proto2_preserve_unknown_enum_unittest.M"
    "yEnum\022A\n\nrepeated_e\030\002 \003(\0162-.proto2_prese"
    "rve_unknown_enum_unittest.MyEnum\022L\n\021repe"
    "ated_packed_e\030\003 \003(\0162-.proto2_preserve_un"
    "known_enum_unittest.MyEnumB\002\020\001\022B\n\toneof_"
    "e_1\030\004 \001(\0162-.proto2_preserve_unknown_enum"
    "_unittest.MyEnumH\000\022B\n\toneof_e_2\030\005 \001(\0162-."
    "proto2_preserve_unknown_enum_unittest.My"
    "EnumH\000B\003\n\001o\"\231\003\n\022MyMessagePlusExtra\022A\n\001e\030"
    "\001 \001(\01626.proto2_preserve_unknown_enum_uni"
    "ttest.MyEnumPlusExtra\022J\n\nrepeated_e\030\002 \003("
    "\01626.proto2_preserve_unknown_enum_unittes"
    "t.MyEnumPlusExtra\022U\n\021repeated_packed_e\030\003"
    " \003(\01626.proto2_preserve_unknown_enum_unit"
    "test.MyEnumPlusExtraB\002\020\001\022K\n\toneof_e_1\030\004 "
    "\001(\01626.proto2_preserve_unknown_enum_unitt"
    "est.MyEnumPlusExtraH\000\022K\n\toneof_e_2\030\005 \001(\016"
    "26.proto2_preserve_unknown_enum_unittest"
    ".MyEnumPlusExtraH\000B\003\n\001o*#\n\006MyEnum\022\007\n\003FOO"
    "\020\000\022\007\n\003BAR\020\001\022\007\n\003BAZ\020\002*\?\n\017MyEnumPlusExtra\022"
    "\t\n\005E_FOO\020\000\022\t\n\005E_BAR\020\001\022\t\n\005E_BAZ\020\002\022\013\n\007E_EX"
    "TRA\020\003b\006proto3", 973);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "google/protobuf/unittest_preserve_unknown_enum.proto", &protobuf_RegisterTypes);
  MyMessage::default_instance_ = new MyMessage();
  MyMessage_default_oneof_instance_ = new MyMessageOneofInstance();
  MyMessagePlusExtra::default_instance_ = new MyMessagePlusExtra();
  MyMessagePlusExtra_default_oneof_instance_ = new MyMessagePlusExtraOneofInstance();
  MyMessage::default_instance_->InitAsDefaultInstance();
  MyMessagePlusExtra::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto {
  StaticDescriptorInitializer_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto() {
    protobuf_AddDesc_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto();
  }
} static_descriptor_initializer_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto_;
const ::google::protobuf::EnumDescriptor* MyEnum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyEnum_descriptor_;
}
bool MyEnum_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MyEnumPlusExtra_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyEnumPlusExtra_descriptor_;
}
bool MyEnumPlusExtra_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int MyMessage::kEFieldNumber;
const int MyMessage::kRepeatedEFieldNumber;
const int MyMessage::kRepeatedPackedEFieldNumber;
const int MyMessage::kOneofE1FieldNumber;
const int MyMessage::kOneofE2FieldNumber;
#endif  // !_MSC_VER

MyMessage::MyMessage()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto2_preserve_unknown_enum_unittest.MyMessage)
}

void MyMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  MyMessage_default_oneof_instance_->oneof_e_1_ = 0;
  MyMessage_default_oneof_instance_->oneof_e_2_ = 0;
}

MyMessage::MyMessage(const MyMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:proto2_preserve_unknown_enum_unittest.MyMessage)
}

void MyMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  e_ = 0;
  clear_has_o();
}

MyMessage::~MyMessage() {
  // @@protoc_insertion_point(destructor:proto2_preserve_unknown_enum_unittest.MyMessage)
  SharedDtor();
}

void MyMessage::SharedDtor() {
  if (has_o()) {
    clear_o();
  }
  if (this != default_instance_) {
  }
}

void MyMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MyMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyMessage_descriptor_;
}

const MyMessage& MyMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto();
  return *default_instance_;
}

MyMessage* MyMessage::default_instance_ = NULL;

MyMessage* MyMessage::New(::google::protobuf::Arena* arena) const {
  MyMessage* n = new MyMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MyMessage::clear_o() {
  switch(o_case()) {
    case kOneofE1: {
      // No need to clear
      break;
    }
    case kOneofE2: {
      // No need to clear
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = O_NOT_SET;
}


void MyMessage::Clear() {
  e_ = 0;
  repeated_e_.Clear();
  repeated_packed_e_.Clear();
  clear_o();
}

bool MyMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto2_preserve_unknown_enum_unittest.MyMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .proto2_preserve_unknown_enum_unittest.MyEnum e = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_e(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnum >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_repeated_e;
        break;
      }

      // repeated .proto2_preserve_unknown_enum_unittest.MyEnum repeated_e = 2;
      case 2: {
        if (tag == 16) {
         parse_repeated_e:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          add_repeated_e(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnum >(value));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedEnumNoInline(
                 input,
                 NULL,
                 this->mutable_repeated_e())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_repeated_e;
        if (input->ExpectTag(26)) goto parse_repeated_packed_e;
        break;
      }

      // repeated .proto2_preserve_unknown_enum_unittest.MyEnum repeated_packed_e = 3 [packed = true];
      case 3: {
        if (tag == 26) {
         parse_repeated_packed_e:
          ::google::protobuf::uint32 length;
          DO_(input->ReadVarint32(&length));
          ::google::protobuf::io::CodedInputStream::Limit limit = input->PushLimit(length);
          while (input->BytesUntilLimit() > 0) {
            int value;
            DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
            add_repeated_packed_e(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnum >(value));
          }
          input->PopLimit(limit);
        } else if (tag == 24) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          add_repeated_packed_e(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnum >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_oneof_e_1;
        break;
      }

      // optional .proto2_preserve_unknown_enum_unittest.MyEnum oneof_e_1 = 4;
      case 4: {
        if (tag == 32) {
         parse_oneof_e_1:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_oneof_e_1(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnum >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_oneof_e_2;
        break;
      }

      // optional .proto2_preserve_unknown_enum_unittest.MyEnum oneof_e_2 = 5;
      case 5: {
        if (tag == 40) {
         parse_oneof_e_2:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_oneof_e_2(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnum >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto2_preserve_unknown_enum_unittest.MyMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto2_preserve_unknown_enum_unittest.MyMessage)
  return false;
#undef DO_
}

void MyMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto2_preserve_unknown_enum_unittest.MyMessage)
  // optional .proto2_preserve_unknown_enum_unittest.MyEnum e = 1;
  if (this->e() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->e(), output);
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnum repeated_e = 2;
  for (int i = 0; i < this->repeated_e_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->repeated_e(i), output);
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnum repeated_packed_e = 3 [packed = true];
  if (this->repeated_packed_e_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      output);
    output->WriteVarint32(_repeated_packed_e_cached_byte_size_);
  }
  for (int i = 0; i < this->repeated_packed_e_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteEnumNoTag(
      this->repeated_packed_e(i), output);
  }

  // optional .proto2_preserve_unknown_enum_unittest.MyEnum oneof_e_1 = 4;
  if (has_oneof_e_1()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->oneof_e_1(), output);
  }

  // optional .proto2_preserve_unknown_enum_unittest.MyEnum oneof_e_2 = 5;
  if (has_oneof_e_2()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->oneof_e_2(), output);
  }

  // @@protoc_insertion_point(serialize_end:proto2_preserve_unknown_enum_unittest.MyMessage)
}

::google::protobuf::uint8* MyMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto2_preserve_unknown_enum_unittest.MyMessage)
  // optional .proto2_preserve_unknown_enum_unittest.MyEnum e = 1;
  if (this->e() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->e(), target);
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnum repeated_e = 2;
  for (int i = 0; i < this->repeated_e_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->repeated_e(i), target);
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnum repeated_packed_e = 3 [packed = true];
  if (this->repeated_packed_e_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(    _repeated_packed_e_cached_byte_size_, target);
  }
  for (int i = 0; i < this->repeated_packed_e_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumNoTagToArray(
      this->repeated_packed_e(i), target);
  }

  // optional .proto2_preserve_unknown_enum_unittest.MyEnum oneof_e_1 = 4;
  if (has_oneof_e_1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->oneof_e_1(), target);
  }

  // optional .proto2_preserve_unknown_enum_unittest.MyEnum oneof_e_2 = 5;
  if (has_oneof_e_2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->oneof_e_2(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:proto2_preserve_unknown_enum_unittest.MyMessage)
  return target;
}

int MyMessage::ByteSize() const {
  int total_size = 0;

  // optional .proto2_preserve_unknown_enum_unittest.MyEnum e = 1;
  if (this->e() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->e());
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnum repeated_e = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->repeated_e_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::EnumSize(
        this->repeated_e(i));
    }
    total_size += 1 * this->repeated_e_size() + data_size;
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnum repeated_packed_e = 3 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->repeated_packed_e_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::EnumSize(
        this->repeated_packed_e(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _repeated_packed_e_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  switch (o_case()) {
    // optional .proto2_preserve_unknown_enum_unittest.MyEnum oneof_e_1 = 4;
    case kOneofE1: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->oneof_e_1());
      break;
    }
    // optional .proto2_preserve_unknown_enum_unittest.MyEnum oneof_e_2 = 5;
    case kOneofE2: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MyMessage::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MyMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MyMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MyMessage::MergeFrom(const MyMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  repeated_e_.MergeFrom(from.repeated_e_);
  repeated_packed_e_.MergeFrom(from.repeated_packed_e_);
  switch (from.o_case()) {
    case kOneofE1: {
      set_oneof_e_1(from.oneof_e_1());
      break;
    }
    case kOneofE2: {
      set_oneof_e_2(from.oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  if (from.e() != 0) {
    set_e(from.e());
  }
}

void MyMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessage::CopyFrom(const MyMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessage::IsInitialized() const {

  return true;
}

void MyMessage::Swap(MyMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MyMessage::InternalSwap(MyMessage* other) {
  std::swap(e_, other->e_);
  repeated_e_.UnsafeArenaSwap(&other->repeated_e_);
  repeated_packed_e_.UnsafeArenaSwap(&other->repeated_packed_e_);
  std::swap(o_, other->o_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MyMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MyMessage_descriptor_;
  metadata.reflection = MyMessage_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MyMessagePlusExtra::kEFieldNumber;
const int MyMessagePlusExtra::kRepeatedEFieldNumber;
const int MyMessagePlusExtra::kRepeatedPackedEFieldNumber;
const int MyMessagePlusExtra::kOneofE1FieldNumber;
const int MyMessagePlusExtra::kOneofE2FieldNumber;
#endif  // !_MSC_VER

MyMessagePlusExtra::MyMessagePlusExtra()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
}

void MyMessagePlusExtra::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  MyMessagePlusExtra_default_oneof_instance_->oneof_e_1_ = 0;
  MyMessagePlusExtra_default_oneof_instance_->oneof_e_2_ = 0;
}

MyMessagePlusExtra::MyMessagePlusExtra(const MyMessagePlusExtra& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
}

void MyMessagePlusExtra::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  e_ = 0;
  clear_has_o();
}

MyMessagePlusExtra::~MyMessagePlusExtra() {
  // @@protoc_insertion_point(destructor:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  SharedDtor();
}

void MyMessagePlusExtra::SharedDtor() {
  if (has_o()) {
    clear_o();
  }
  if (this != default_instance_) {
  }
}

void MyMessagePlusExtra::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MyMessagePlusExtra::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyMessagePlusExtra_descriptor_;
}

const MyMessagePlusExtra& MyMessagePlusExtra::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto();
  return *default_instance_;
}

MyMessagePlusExtra* MyMessagePlusExtra::default_instance_ = NULL;

MyMessagePlusExtra* MyMessagePlusExtra::New(::google::protobuf::Arena* arena) const {
  MyMessagePlusExtra* n = new MyMessagePlusExtra;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MyMessagePlusExtra::clear_o() {
  switch(o_case()) {
    case kOneofE1: {
      // No need to clear
      break;
    }
    case kOneofE2: {
      // No need to clear
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = O_NOT_SET;
}


void MyMessagePlusExtra::Clear() {
  e_ = 0;
  repeated_e_.Clear();
  repeated_packed_e_.Clear();
  clear_o();
}

bool MyMessagePlusExtra::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra e = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_e(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnumPlusExtra >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_repeated_e;
        break;
      }

      // repeated .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_e = 2;
      case 2: {
        if (tag == 16) {
         parse_repeated_e:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          add_repeated_e(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnumPlusExtra >(value));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedEnumNoInline(
                 input,
                 NULL,
                 this->mutable_repeated_e())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_repeated_e;
        if (input->ExpectTag(26)) goto parse_repeated_packed_e;
        break;
      }

      // repeated .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_e = 3 [packed = true];
      case 3: {
        if (tag == 26) {
         parse_repeated_packed_e:
          ::google::protobuf::uint32 length;
          DO_(input->ReadVarint32(&length));
          ::google::protobuf::io::CodedInputStream::Limit limit = input->PushLimit(length);
          while (input->BytesUntilLimit() > 0) {
            int value;
            DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
            add_repeated_packed_e(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnumPlusExtra >(value));
          }
          input->PopLimit(limit);
        } else if (tag == 24) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          add_repeated_packed_e(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnumPlusExtra >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_oneof_e_1;
        break;
      }

      // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_1 = 4;
      case 4: {
        if (tag == 32) {
         parse_oneof_e_1:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_oneof_e_1(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnumPlusExtra >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_oneof_e_2;
        break;
      }

      // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_2 = 5;
      case 5: {
        if (tag == 40) {
         parse_oneof_e_2:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_oneof_e_2(static_cast< ::proto2_preserve_unknown_enum_unittest::MyEnumPlusExtra >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  return false;
#undef DO_
}

void MyMessagePlusExtra::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra e = 1;
  if (this->e() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->e(), output);
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_e = 2;
  for (int i = 0; i < this->repeated_e_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->repeated_e(i), output);
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_e = 3 [packed = true];
  if (this->repeated_packed_e_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      output);
    output->WriteVarint32(_repeated_packed_e_cached_byte_size_);
  }
  for (int i = 0; i < this->repeated_packed_e_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteEnumNoTag(
      this->repeated_packed_e(i), output);
  }

  // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_1 = 4;
  if (has_oneof_e_1()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->oneof_e_1(), output);
  }

  // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_2 = 5;
  if (has_oneof_e_2()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->oneof_e_2(), output);
  }

  // @@protoc_insertion_point(serialize_end:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
}

::google::protobuf::uint8* MyMessagePlusExtra::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra e = 1;
  if (this->e() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->e(), target);
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_e = 2;
  for (int i = 0; i < this->repeated_e_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->repeated_e(i), target);
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_e = 3 [packed = true];
  if (this->repeated_packed_e_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(    _repeated_packed_e_cached_byte_size_, target);
  }
  for (int i = 0; i < this->repeated_packed_e_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumNoTagToArray(
      this->repeated_packed_e(i), target);
  }

  // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_1 = 4;
  if (has_oneof_e_1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->oneof_e_1(), target);
  }

  // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_2 = 5;
  if (has_oneof_e_2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->oneof_e_2(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:proto2_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  return target;
}

int MyMessagePlusExtra::ByteSize() const {
  int total_size = 0;

  // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra e = 1;
  if (this->e() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->e());
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_e = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->repeated_e_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::EnumSize(
        this->repeated_e(i));
    }
    total_size += 1 * this->repeated_e_size() + data_size;
  }

  // repeated .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_e = 3 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->repeated_packed_e_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::EnumSize(
        this->repeated_packed_e(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _repeated_packed_e_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  switch (o_case()) {
    // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_1 = 4;
    case kOneofE1: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->oneof_e_1());
      break;
    }
    // optional .proto2_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_2 = 5;
    case kOneofE2: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MyMessagePlusExtra::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MyMessagePlusExtra* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MyMessagePlusExtra*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MyMessagePlusExtra::MergeFrom(const MyMessagePlusExtra& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  repeated_e_.MergeFrom(from.repeated_e_);
  repeated_packed_e_.MergeFrom(from.repeated_packed_e_);
  switch (from.o_case()) {
    case kOneofE1: {
      set_oneof_e_1(from.oneof_e_1());
      break;
    }
    case kOneofE2: {
      set_oneof_e_2(from.oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  if (from.e() != 0) {
    set_e(from.e());
  }
}

void MyMessagePlusExtra::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessagePlusExtra::CopyFrom(const MyMessagePlusExtra& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessagePlusExtra::IsInitialized() const {

  return true;
}

void MyMessagePlusExtra::Swap(MyMessagePlusExtra* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MyMessagePlusExtra::InternalSwap(MyMessagePlusExtra* other) {
  std::swap(e_, other->e_);
  repeated_e_.UnsafeArenaSwap(&other->repeated_e_);
  repeated_packed_e_.UnsafeArenaSwap(&other->repeated_packed_e_);
  std::swap(o_, other->o_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MyMessagePlusExtra::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MyMessagePlusExtra_descriptor_;
  metadata.reflection = MyMessagePlusExtra_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto2_preserve_unknown_enum_unittest

// @@protoc_insertion_point(global_scope)
